version: '3.8'

services:
  nginx19:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/data
    depends_on:
      - app19
      - rabbitmq19

  app19:
    build:
      context: .docker/fpm
      dockerfile: Dockerfile
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      QUEUE: ${QUEUE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - ./app:/data
    depends_on:
      - mysql19
      - rabbitmq19

  consumer19:
    build:
      context: .docker/fpm
      dockerfile: Dockerfile
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      QUEUE: ${QUEUE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - ./app:/data
    depends_on:
      - mysql19
      - rabbitmq19

  rabbitmq19:
    image: rabbitmq:3.7.7-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "127.0.0.1:5673:5672"
      - "127.0.0.1:15673:15672"

  mysql19:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - data19:/var/lib/mysql

volumes:
  data19:
